### ISSUE TITLE
Email input field and button is missing 

### ISSUE THREAD

**Issue by computangit** [computangit/radiantmarketing-lifescapepremier#77]
**URL tested:** http://staging.lifescapepremier.com/new-home/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Firefox&browser_version=72.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fstaging.lifescapepremier.com%2Fnew-home%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://staging.lifescapepremier.com/new-home/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Firefox 72.0 |
| Operating System | Windows 10 |
| Resolution | 1536x754 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/bd06d02fcd01a1d98f38d5b92cafd5100938ebb1/win10_firefox_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/bd06d02fcd01a1d98f38d5b92cafd5100938ebb1/win10_firefox_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=Firefox&browser_version=72.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fstaging.lifescapepremier.com%2Fnew-home%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://staging.lifescapepremier.com/new-home/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by computangit** [comment]
There we use HS form, Need help from HS team.
Sajjad Ali Khan.

**Comment by computangit** [comment]
Fixed
Sajjad Ali Khan

**Comment by farhan-arshad-com** [comment]
Verify and closed
