### ISSUE TITLE
Next/previous buttons are missing 

### ISSUE THREAD

**Issue by computangit** [computangit/radiantmarketing-lifescapepremier#81]
**URL tested:** http://staging.lifescapepremier.com/new-home/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=13.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fstaging.lifescapepremier.com%2Fnew-home%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://staging.lifescapepremier.com/new-home/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XS |
| Browser | Mobile_safari |
| Operating System | iOS 13.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in - 2.79 x 5.65 in |
| Viewport | 375 x 812 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5b33c6e989ac7ecedb0d7b40bc314710e7958c45/realios_iPhone_XS.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5b33c6e989ac7ecedb0d7b40bc314710e7958c45/realios_iPhone_XS.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=13.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fstaging.lifescapepremier.com%2Fnew-home%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://staging.lifescapepremier.com/new-home/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by computangit** [comment]
Fixed
Sajjad Ali Khan

**Comment by farhan-arshad-com** [comment]
Verify and closed
