### ISSUE TITLE
When rotate the device then some heading are showing in center and some are showing on left  side

### ISSUE THREAD

**Issue by computangit** [computangit/radiantmarketing-lifescapepremier#87]
**URL tested:** http://staging.lifescapepremier.com/new-home/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fstaging.lifescapepremier.com%2Fnew-home%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://staging.lifescapepremier.com/new-home/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c21ef0dd3c924f05ea19b4c3878fc89e7aea8a84/realios_iPhone_8.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c21ef0dd3c924f05ea19b4c3878fc89e7aea8a84/realios_iPhone_8.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fstaging.lifescapepremier.com%2Fnew-home%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://staging.lifescapepremier.com/new-home/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by computangit** [comment]
Fixed
Sajjad Ali Khan

**Comment by farhan-arshad-com** [comment]
Verify and closed
